### ISSUE TITLE
Add resolve function later

### ISSUE THREAD

**Issue by serle** [bloveit/graphql-utilities#14]
Would it be possible to provide an API to add the resolve functions onto the build output at a later point in time. I would prefer to keep my data type specification separate from the details of resolution.

**Comment by migueloller** [comment]
Hi @serle,

I just saw this issue, I apologize for the late response.

It would be possible to modify the GraphQL type after the fact, but keep in mind there's nothing stopping you from separating your type definitions from your resolvers. You could even have a `MyType.graphql` file and write a small utility function that uses a `.graphql` file for the type definitions and a `MyType.js` file for the resolvers.

**Comment by serle** [comment]
Thx @migueloller 

I have created a small function that provides a promise to assembles all my `.graphql` and `.js` makes the executable `GraphQL` schema. Once the promise resolves I start the GraphQL server. I ended up using the dynamic module loading functionality to load in the "resolve" javascript modules.

**Comment by migueloller** [comment]
Here's a quick example of a function that does it synchronously:

```js
/* build.js */

const utilities = require('graphql-utilities')
const fs = require('fs')

const build = (...args) =>
  utilities.build(fs.readFileSync(__filename.replace(/\.js$/, '.graphql'), 'utf-8'), ...args)
```

You can then have the following directory structure:

```
/src
  |-- build.js
  |-- MyType.js
  `-- MyType.graphql
```

And `MyType.js` is as simple as:

```js
const build = require('./build')

module.exports = build(/* config, typeDependencies */) // GraphQLObjectType
```

**Comment by serle** [comment]
My get options function that returns the promise using micro:

`const APOLLO = true;
const options_promise = get_options('./src/schema', graph_root, true, true, true);

exports.default = async (req, res) => {

   return APOLLO ? microGraphql(await options_promise)(req, res) : graphqlHTTP(await options_promise)(req, res);
};
`
